name: Renovate
on:
  schedule:
    - cron: "0 7,17 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ steps.token.outputs.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          LOG_LEVEL: info
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: "43.136.1"
        run: npx --yes "renovate@${RENOVATE_VERSION}"
